プライベートモード時にリアクションのカウントを非表示する
Yudai-Saito/Homete pull request #272
Opened 2022-12-03 09:16 UTC by shiratoriren

一緒に、
Googleでログインの表示を先頭だけ大文字に変更
三点リーダーを押した際に本人の投稿の時は削除が表示されるように変更
通報、削除ボタンを押した際に表示されるオーバーレイを作成
<img width="1047" alt="スクリーンショット 2022-12-03 18 16 22" src="https://user-images.githubusercontent.com/60804269/205433646-dcf7e44d-9528-47de-9ea9-6eb89e6310e1.png">
<img width="1049" alt="スクリーンショット 2022-12-03 18 02 57" src="https://user-images.githubusercontent.com/60804269/205433172-ae4417a5-ba2f-42db-b282-7c42d29608b7.png">
<img width="1048" alt="スクリーンショット 2022-12-03 18 02 50" src="https://user-images.githubusercontent.com/60804269/205433175-d66fb6e3-3786-479a-9ee6-599f2b4ee317.png">

2022-12-03 14:04 UTC, Yudai-Saito requested changes
DRY原則。大事。

2022-12-03 14:04 UTC, Yudai-Saito commented on frontend/src/views/NotFound.vue
> +      />
ここも共通化しちゃいましょ！

2022-12-03 14:04 UTC, Yudai-Saito commented on frontend/src/views/About.vue
> +      />
ログイン部分で使い回しあるので、短いかもですけど、Login.vueとかでまとめた方が良いかと思いました！

DRY原則（Don't Repeat Yourself) 同じ意味を持つ処理を複数ファイルに置かないほうが、１つ変更すれば全て変更できるから便利だよね！っていう思想があるので、覚えておくと良きかもです！

バックエンドもDRY原則従ってない所あるんで、書いてから気づいて共通化していくってことが多いです！
DRY原則探し！まさしくこれがレビューアーの仕事な気がします！

2022-12-03 14:04 UTC, Yudai-Saito commented on frontend/src/views/AccountManagement.vue
> +      />
ここも共通化しちゃいましょ！

2022-12-03 14:04 UTC, Yudai-Saito commented on frontend/src/views/Top.vue
> +      />
ここも共通化しちゃいましょ！

2022-12-03 14:26 UTC, Yudai-Saito commented
![image](https://user-images.githubusercontent.com/42965816/205445730-d9171387-4d63-449d-ab2b-7c6571f54910.png)
アカウント管理画面でオーバレイが表示されてしまう

2022-12-03 14:26 UTC, Yudai-Saito commented
![image](https://user-images.githubusercontent.com/42965816/205445752-45802739-becc-4e42-9fe2-f6a79449bdd3.png)
404NOTFOUNTでオーバレイが表示されてしまう

2022-12-03 14:26 UTC, Yudai-Saito commented
![image](https://user-images.githubusercontent.com/42965816/205445772-3d95d01e-77cf-4c0b-a0a0-f20ecadf68f5.png)
aboutでオーバレイが表示されてしまう

2022-12-03 14:32 UTC, Yudai-Saito requested changes
インポートミスがありました！

2022-12-03 14:32 UTC, Yudai-Saito commented on frontend/src/views/AccountManagement.vue
> +import CommonOverlay from "@/components/Account/CommonOverlay.vue";
```javascript
import CommonOverlay from "@/components/util/CommonOverlay.vue";
```
に修正してください！

2022-12-03 14:32 UTC, Yudai-Saito commented on frontend/src/views/About.vue
> +import CommonOverlay from "@/components/Account/CommonOverlay.vue";
```javascript
import CommonOverlay from "@/components/util/CommonOverlay.vue";
```
に修正してください！

2022-12-03 14:32 UTC, Yudai-Saito commented on frontend/src/views/NotFound.vue
> +import CommonOverlay from "@/components/Account/CommonOverlay.vue";
```javascript
import CommonOverlay from "@/components/util/CommonOverlay.vue";
```
に修正してください！

2022-12-03 14:32 UTC, Yudai-Saito commented on frontend/src/views/Top.vue
> +import CommonOverlay from "@/components/Account/CommonOverlay.vue";
```javascript
import CommonOverlay from "@/components/util/CommonOverlay.vue";
```
に修正してください！

2022-12-03 14:44 UTC, Yudai-Saito commented on frontend/src/views/About.vue
> +      :value="displayCommonOverlay"
TOPで使われてるものと違うけどこれはOKなの？

2022-12-03 14:44 UTC, Yudai-Saito commented on frontend/src/views/AccountManagement.vue
> +      :value="displayCommonOverlay"
TOPで使われてるものと違うけどこれはOKなの？

2022-12-03 14:44 UTC, Yudai-Saito commented on frontend/src/views/NotFound.vue
> +      :value="displayCommonOverlay"
TOPで使われてるものと違うけどこれはOKなの？

2022-12-03 14:44 UTC, Yudai-Saito commented on frontend/src/views/Top.vue
> +      :value="overlayState == 'login'"
他で使われてるものと違うけどこれはOKなの？

2022-12-04 07:00 UTC, shiratoriren commented
<img width="1038" alt="スクリーンショット 2022-12-04 15 58 09" src="https://user-images.githubusercontent.com/60804269/205478626-2348f893-2c82-452e-86c3-fbd66ff2d013.png">

2022-12-04 07:37 UTC, Yudai-Saito approved these changes

2022-12-04 07:38 UTC, merged